flatcoke:
  image: flatcoke:latest
  volumes:
    - .:/depoly/flatcoke
  expose:
    - "5000"
nginx:
  image: nginx:latest
  links:
    - flatcoke:uwsgi
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
